sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
before_install:
  - npm i -g npm@^3.7
before_script:
  - npm prune
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start